env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:tailwindcss/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  tailwindcss/no-custom-classname: off

plugins:
  - react
  - import

settings:
  react:
    version: detect
  # tailwindcss:
  #   classRegex: accent-*

  'import/resolver':
    node:
      paths:
        - src
      extentions:
        - js
        - jsx
        - ts
        - tsx
